stages:          # List of stages for jobs, and their order of execution
  - build
  - test


build-job:
  stage: build
  script:
    - ./scripts/build.sh 

test_job:
  stage: test
  script:
    - ./scripts/test.sh 
